import{fragment,vertex}from"./shaders";
const shader=(gl:WebGL2RenderingContext,type:number,src:string)=>{const s=gl.createShader(type)!;gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s)??"Shader failure");return s};
const perspective=(aspect:number)=>{const f=1/Math.tan(.55);const near=.1,far=20;return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)/(near-far),-1,0,0,2*far*near/(near-far),0])};
export class Renderer{private gl:WebGL2RenderingContext;private program:WebGLProgram;private pos:WebGLBuffer;private norm:WebGLBuffer;private uv:WebGLBuffer;private idx:WebGLBuffer;private texture:WebGLTexture;private count=0;
constructor(private canvas:HTMLCanvasElement){const gl=canvas.getContext("webgl2",{antialias:true,alpha:false});if(!gl)throw new Error("WebGL2 is required");this.gl=gl;const p=gl.createProgram()!;gl.attachShader(p,shader(gl,gl.VERTEX_SHADER,vertex));gl.attachShader(p,shader(gl,gl.FRAGMENT_SHADER,fragment));gl.linkProgram(p);if(!gl.getProgramParameter(p,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(p)??"Link failure");this.program=p;this.pos=gl.createBuffer()!;this.norm=gl.createBuffer()!;this.uv=gl.createBuffer()!;this.idx=gl.createBuffer()!;this.texture=gl.createTexture()!;this.defaultTexture();gl.enable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE)}
setMesh(positions:Float32Array,normals:Float32Array,indices:Uint32Array,w:number,h:number){const g=this.gl;this.count=indices.length;g.bindBuffer(g.ARRAY_BUFFER,this.pos);g.bufferData(g.ARRAY_BUFFER,positions,g.DYNAMIC_DRAW);g.bindBuffer(g.ARRAY_BUFFER,this.norm);g.bufferData(g.ARRAY_BUFFER,normals,g.DYNAMIC_DRAW);const uv=new Float32Array(w*h*2);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const i=(y*w+x)*2;uv[i]=x/(w-1);uv[i+1]=y/(h-1)}g.bindBuffer(g.ARRAY_BUFFER,this.uv);g.bufferData(g.ARRAY_BUFFER,uv,g.STATIC_DRAW);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,this.idx);g.bufferData(g.ELEMENT_ARRAY_BUFFER,indices,g.STATIC_DRAW)}
update(positions:Float32Array,normals:Float32Array){const g=this.gl;g.bindBuffer(g.ARRAY_BUFFER,this.pos);g.bufferSubData(g.ARRAY_BUFFER,0,positions);g.bindBuffer(g.ARRAY_BUFFER,this.norm);g.bufferSubData(g.ARRAY_BUFFER,0,normals)}
render(){this.resize();const g=this.gl;g.viewport(0,0,this.canvas.width,this.canvas.height);g.clearColor(.025,.047,.044,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);g.useProgram(this.program);const bind=(b:WebGLBuffer,i:number,n:number)=>{g.bindBuffer(g.ARRAY_BUFFER,b);g.enableVertexAttribArray(i);g.vertexAttribPointer(i,n,g.FLOAT,false,0,0)};bind(this.pos,0,3);bind(this.norm,1,3);bind(this.uv,2,2);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,this.idx);g.uniformMatrix4fv(g.getUniformLocation(this.program,"projection"),false,perspective(this.canvas.width/this.canvas.height));g.uniformMatrix4fv(g.getUniformLocation(this.program,"view"),false,new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,-1.25,0,-4.4,1]));g.drawElements(g.TRIANGLES,this.count,g.UNSIGNED_INT,0)}
setImage(image:TexImageSource){const g=this.gl;g.bindTexture(g.TEXTURE_2D,this.texture);g.pixelStorei(g.UNPACK_FLIP_Y_WEBGL,0);g.texImage2D(g.TEXTURE_2D,0,g.RGBA,g.RGBA,g.UNSIGNED_BYTE,image);g.generateMipmap(g.TEXTURE_2D)}
private defaultTexture(){const c=document.createElement("canvas");c.width=1024;c.height=640;const x=c.getContext("2d")!;x.fillStyle="#e9e2cd";x.fillRect(0,0,c.width,c.height);x.fillStyle="#dd523f";x.fillRect(0,0,290,c.height);x.fillStyle="#102c28";x.font="700 76px system-ui";x.fillText("WASM",350,280);x.font="42px system-ui";x.fillText("CLOTH LAB",350,350);x.strokeStyle="rgba(16,44,40,.14)";x.lineWidth=2;for(let i=0;i<=16;i++){x.beginPath();x.moveTo(i*64,0);x.lineTo(i*64,640);x.stroke()}for(let i=0;i<=10;i++){x.beginPath();x.moveTo(0,i*64);x.lineTo(1024,i*64);x.stroke()}this.setImage(c);const g=this.gl;g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.LINEAR_MIPMAP_LINEAR);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.LINEAR)}
private resize(){const d=Math.min(devicePixelRatio,2),w=Math.round(this.canvas.clientWidth*d),h=Math.round(this.canvas.clientHeight*d);if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}}
}
